/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CallRouteImport } from './routes/call'
import { Route as AdRouteImport } from './routes/ad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaceIdRouteImport } from './routes/place.$id'
import { Route as DirectionsIdRouteImport } from './routes/directions.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as PlaceIdDetailsRouteImport } from './routes/place.$id.details'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const AdRoute = AdRouteImport.update({
  id: '/ad',
  path: '/ad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdRoute = PlaceIdRouteImport.update({
  id: '/place/$id',
  path: '/place/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsIdRoute = DirectionsIdRouteImport.update({
  id: '/directions/$id',
  path: '/directions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdDetailsRoute = PlaceIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => PlaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ad': typeof AdRoute
  '/call': typeof CallRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/directions/$id': typeof DirectionsIdRoute
  '/place/$id': typeof PlaceIdRouteWithChildren
  '/place/$id/details': typeof PlaceIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ad': typeof AdRoute
  '/call': typeof CallRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/directions/$id': typeof DirectionsIdRoute
  '/place/$id': typeof PlaceIdRouteWithChildren
  '/place/$id/details': typeof PlaceIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ad': typeof AdRoute
  '/call': typeof CallRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/directions/$id': typeof DirectionsIdRoute
  '/place/$id': typeof PlaceIdRouteWithChildren
  '/place/$id/details': typeof PlaceIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ad'
    | '/call'
    | '/explore'
    | '/favorites'
    | '/home'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/reviews'
    | '/search'
    | '/settings'
    | '/category/$slug'
    | '/directions/$id'
    | '/place/$id'
    | '/place/$id/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ad'
    | '/call'
    | '/explore'
    | '/favorites'
    | '/home'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/reviews'
    | '/search'
    | '/settings'
    | '/category/$slug'
    | '/directions/$id'
    | '/place/$id'
    | '/place/$id/details'
  id:
    | '__root__'
    | '/'
    | '/ad'
    | '/call'
    | '/explore'
    | '/favorites'
    | '/home'
    | '/onboarding'
    | '/planner'
    | '/profile'
    | '/reviews'
    | '/search'
    | '/settings'
    | '/category/$slug'
    | '/directions/$id'
    | '/place/$id'
    | '/place/$id/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdRoute: typeof AdRoute
  CallRoute: typeof CallRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DirectionsIdRoute: typeof DirectionsIdRoute
  PlaceIdRoute: typeof PlaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad': {
      id: '/ad'
      path: '/ad'
      fullPath: '/ad'
      preLoaderRoute: typeof AdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$id': {
      id: '/place/$id'
      path: '/place/$id'
      fullPath: '/place/$id'
      preLoaderRoute: typeof PlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions/$id': {
      id: '/directions/$id'
      path: '/directions/$id'
      fullPath: '/directions/$id'
      preLoaderRoute: typeof DirectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$id/details': {
      id: '/place/$id/details'
      path: '/details'
      fullPath: '/place/$id/details'
      preLoaderRoute: typeof PlaceIdDetailsRouteImport
      parentRoute: typeof PlaceIdRoute
    }
  }
}

interface PlaceIdRouteChildren {
  PlaceIdDetailsRoute: typeof PlaceIdDetailsRoute
}

const PlaceIdRouteChildren: PlaceIdRouteChildren = {
  PlaceIdDetailsRoute: PlaceIdDetailsRoute,
}

const PlaceIdRouteWithChildren =
  PlaceIdRoute._addFileChildren(PlaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdRoute: AdRoute,
  CallRoute: CallRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  CategorySlugRoute: CategorySlugRoute,
  DirectionsIdRoute: DirectionsIdRoute,
  PlaceIdRoute: PlaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
